# 한국어 데이터셋 구조 점검

다운로드한 `data/raw`의 Parquet·JSONL 파일을 메모리에 한꺼번에 올리지 않고 점검합니다.

확인 항목:
- 파일별 크기·행 수·컬럼
- 데이터 샘플과 중첩 구조
- 결측치와 컬럼 타입
- 대화 데이터의 role 분포
- 텍스트 길이 분포

In [1]:
from pathlib import Path
import json
from collections import Counter

import pandas as pd
import pyarrow.parquet as pq
from IPython.display import display

ROOT = Path.cwd()
RAW_DIR = ROOT / 'data' / 'raw'
SAMPLE_ROWS = 2_000

if not RAW_DIR.exists():
    raise FileNotFoundError(f'데이터 폴더가 없습니다: {RAW_DIR}')

print(f'프로젝트: {ROOT}')
print(f'데이터 폴더: {RAW_DIR}')

프로젝트: c:\Users\User\Desktop\trans
데이터 폴더: c:\Users\User\Desktop\trans\data\raw

## 1. 파일 인벤토리

In [2]:
def parquet_info(path):
    pf = pq.ParquetFile(path)
    return {
        'dataset': path.relative_to(RAW_DIR).parts[0],
        'file': path.relative_to(ROOT).as_posix(),
        'format': 'parquet',
        'rows': pf.metadata.num_rows,
        'size_mb': round(path.stat().st_size / 1024**2, 2),
        'columns': ', '.join(pf.schema_arrow.names),
    }

def jsonl_info(path):
    rows = 0
    keys = set()
    with path.open(encoding='utf-8') as f:
        for line in f:
            if line.strip():
                rows += 1
                if rows <= 1000:
                    value = json.loads(line)
                    if isinstance(value, dict):
                        keys.update(value.keys())
    return {
        'dataset': path.relative_to(RAW_DIR).parts[0],
        'file': path.relative_to(ROOT).as_posix(),
        'format': 'jsonl',
        'rows': rows,
        'size_mb': round(path.stat().st_size / 1024**2, 2),
        'columns': ', '.join(sorted(keys)),
    }

files = sorted(p for p in RAW_DIR.rglob('*') if p.is_file() and '.cache' not in p.parts)
inventory = []
for path in files:
    if path.suffix == '.parquet':
        inventory.append(parquet_info(path))
    elif path.suffix == '.jsonl':
        inventory.append(jsonl_info(path))

inventory_df = pd.DataFrame(inventory)
display(inventory_df)
print(f'파일 수: {len(inventory_df)}, 총 행 수: {inventory_df.rows.sum():,}')

,dataset,file,format,rows,size_mb,columns
0,beomi,data/raw/beomi/KoAlpaca-RealQA/data/train-0000...,parquet,18524,13.34,"custom_id, question, answer"
1,developer-lunark,data/raw/developer-lunark/korean-character-rol...,parquet,108,0.03,"id, messages, metadata"
2,developer-lunark,data/raw/developer-lunark/korean-character-rol...,parquet,965,0.16,"id, messages, metadata"
3,huggingface-krew,data/raw/huggingface-krew/korean-role-playing/...,parquet,890,0.41,"text, topic"
4,huggingface-krew,data/raw/huggingface-krew/korean-role-playing/...,parquet,32367,91.91,text
5,huggingface-krew,data/raw/huggingface-krew/korean-role-playing/...,parquet,1920,1.57,text
6,junidude14,data/raw/junidude14/korean_roleplay_dataset_fo...,parquet,25568,2.61,"instruction, input, output"
7,lemon-mint,data/raw/lemon-mint/Korean-FineTome-100k/data/...,parquet,50000,118.18,messages
8,lemon-mint,data/raw/lemon-mint/Korean-FineTome-100k/data/...,parquet,50000,114.65,messages
9,lemon-mint,data/raw/lemon-mint/smol-koreantalk/data/train...,parquet,57536,232.69,"messages, custom_id"
10,lemon-mint,data/raw/lemon-mint/smol-koreantalk/data/train...,parquet,57535,234.77,"messages, custom_id"
11,lemon-mint,data/raw/lemon-mint/smol-koreantalk/data/train...,parquet,57535,233.22,"messages, custom_id"
12,lemon-mint,data/raw/lemon-mint/smol-koreantalk/data/train...,parquet,57535,235.07,"messages, custom_id"
13,lemon-mint,data/raw/lemon-mint/smol-koreantalk/data/train...,parquet,57535,234.79,"messages, custom_id"
14,lemon-mint,data/raw/lemon-mint/smol-koreantalk/data/train...,parquet,57535,234.17,"messages, custom_id"
15,lemon-mint,data/raw/lemon-mint/smol-koreantalk/data/train...,parquet,57535,236.44,"messages, custom_id"
16,lemon-mint,data/raw/lemon-mint/smol-koreantalk/data/train...,parquet,57535,235.08,"messages, custom_id"
17,mkd-chanwoo,data/raw/mkd-chanwoo/keural-rag-chatml-ko/keur...,jsonl,303355,1885.25,"license, n_tokens, source_name, text"

파일 수: 18, 총 행 수: 943,978

## 2. Parquet 스키마와 첫 샘플

`iter_batches`를 사용하므로 대형 파일도 첫 배치만 읽습니다.

In [3]:
parquet_paths = sorted(RAW_DIR.rglob('*.parquet'))
parquet_schema = []
parquet_samples = {}

for path in parquet_paths:
    pf = pq.ParquetFile(path)
    schema = pf.schema_arrow
    parquet_schema.append({
        'file': path.relative_to(ROOT).as_posix(),
        'rows': pf.metadata.num_rows,
        'columns': schema.names,
        'types': [str(schema.field(name).type) for name in schema.names],
    })
    batch = next(pf.iter_batches(batch_size=5), None)
    parquet_samples[path.name] = batch.to_pandas() if batch is not None else pd.DataFrame()

schema_df = pd.DataFrame(parquet_schema)
display(schema_df[['file', 'rows', 'columns', 'types']])

for name, sample in parquet_samples.items():
    print(f'--- {name} ---')
    display(sample)

,file,rows,columns,types
0,data/raw/beomi/KoAlpaca-RealQA/data/train-0000...,18524,"[custom_id, question, answer]","[string, string, string]"
1,data/raw/developer-lunark/korean-character-rol...,108,"[id, messages, metadata]","[string, list<element: struct<content: string,..."
2,data/raw/developer-lunark/korean-character-rol...,965,"[id, messages, metadata]","[string, list<element: struct<content: string,..."
3,data/raw/huggingface-krew/korean-role-playing/...,890,"[text, topic]","[list<element: struct<content: string, role: s..."
4,data/raw/huggingface-krew/korean-role-playing/...,32367,[text],"[list<element: struct<content: string, role: s..."
5,data/raw/huggingface-krew/korean-role-playing/...,1920,[text],"[list<element: struct<content: string, role: s..."
6,data/raw/junidude14/korean_roleplay_dataset_fo...,25568,"[instruction, input, output]","[string, string, string]"
7,data/raw/lemon-mint/Korean-FineTome-100k/data/...,50000,[messages],"[list<element: struct<content: string, content..."
8,data/raw/lemon-mint/Korean-FineTome-100k/data/...,50000,[messages],"[list<element: struct<content: string, content..."
9,data/raw/lemon-mint/smol-koreantalk/data/train...,57536,"[messages, custom_id]","[list<element: struct<content: string, content..."
10,data/raw/lemon-mint/smol-koreantalk/data/train...,57535,"[messages, custom_id]","[list<element: struct<content: string, content..."
11,data/raw/lemon-mint/smol-koreantalk/data/train...,57535,"[messages, custom_id]","[list<element: struct<content: string, content..."
12,data/raw/lemon-mint/smol-koreantalk/data/train...,57535,"[messages, custom_id]","[list<element: struct<content: string, content..."
13,data/raw/lemon-mint/smol-koreantalk/data/train...,57535,"[messages, custom_id]","[list<element: struct<content: string, content..."
14,data/raw/lemon-mint/smol-koreantalk/data/train...,57535,"[messages, custom_id]","[list<element: struct<content: string, content..."
15,data/raw/lemon-mint/smol-koreantalk/data/train...,57535,"[messages, custom_id]","[list<element: struct<content: string, content..."
16,data/raw/lemon-mint/smol-koreantalk/data/train...,57535,"[messages, custom_id]","[list<element: struct<content: string, content..."

--- train-00000-of-00001.parquet ---

,instruction,input,output
0,너는 유저에게 호감도 low을 느끼는 NPC 하정이야. 상황에 맞게 반응해.,USR: 이 스케치 진짜 맘에 안 드는데… 뭐라고 해줄 거야?,솔직히 말해도 돼? 네 작품들 다 비슷해 보이네.
1,너는 유저에게 호감도 low을 느끼는 NPC 하정이야. 상황에 맞게 반응해.,USR: 이 스케치 진짜 맘에 안 드는데… 뭐라고 해줄 거야?\nNPC: 솔직히 말...,네가 의견을 묻길래 말한 거야. 기분 나쁘면 안 물어볼 걸.
2,너는 유저에게 호감도 low을 느끼는 NPC 하정이야. 상황에 맞게 반응해.,USR: 이 스케치 진짜 맘에 안 드는데… 뭐라고 해줄 거야?\nNPC: 솔직히 말...,신중하게 말하자면… 진짜 별로야. 만족스러워?
3,너는 유저에게 호감도 low을 느끼는 NPC 하정이야. 상황에 맞게 반응해.,USR: 이 스케치 진짜 맘에 안 드는데… 뭐라고 해줄 거야?\nNPC: 솔직히 말...,나도 네 반응 보는 게 재미있어서 그래.
4,너는 유저에게 호감도 low을 느끼는 NPC 하정이야. 상황에 맞게 반응해.,USR: 이 스케치 진짜 맘에 안 드는데… 뭐라고 해줄 거야?\nNPC: 솔직히 말...,마음대로 해. 내가 뭘 바라는 것도 아니고.

--- test-00000-of-00001.parquet ---

,id,messages,metadata
0,boost_백이겸_191731_9985,"[{'content': '네 꿈이 뭐야?', 'role': 'user'}, {'co...","{'augmentation': None, 'axis': None, 'b_grade_..."
1,boost2_백이겸_2,"[{'content': '네 이야기 해줘', 'role': 'user'}, {'co...","{'augmentation': None, 'axis': None, 'b_grade_..."
2,target_차도하_24,"[{'content': '좋아하는 거 알려줘', 'role': 'user'}, {'...","{'augmentation': None, 'axis': None, 'b_grade_..."
3,scaled_백이겸_6,"[{'content': '싫어하는 건?', 'role': 'user'}, {'con...","{'augmentation': None, 'axis': None, 'b_grade_..."
4,nearA_박현우_13,"[{'content': '요즘 어때?', 'role': 'user'}, {'cont...","{'augmentation': None, 'axis': None, 'b_grade_..."

--- train-00000-of-00002.parquet ---

                                            messages
0  [{'content': '부울 연산자가 무엇인지, 어떤 역할을 하는지 설명하고, 프...
1  [{'content': '재귀가 어떻게 작동하는지 설명하고, 주어진 숫자의 팩토리얼...
2  [{'content': '부울 연산자가 무엇인지, 어떤 역할을 하는지 설명하고, 프...
3  [{'content': '재귀의 개념을 예시와 함께 설명하고, 선택한 프로그래밍 언...
4  [{'content': 'for 루프를 사용하여 문자열을 반전하여 출력해 주세요.'...

--- train-00001-of-00002.parquet ---

                                            messages
0  [{'content': '당신은 중세 판타지 세계의 마법사예요', 'content_...
1  [{'content': '이 과제에서는, 문단이 주어지고, 그 목표는 문단에서 사건...
2  [{'content': '귀하는 사용자가 IKEA 가구를 조립하는 것을 돕도록 훈련...
3  [{'content': '열을 방출하는 반응이 반응물의 엔탈피가 생성물의 엔탈피보다...
4  [{'content': '다음 과제를 해결하는 Python 코드를 작성해주세요:
문...

--- train-00000-of-00008.parquet ---

                                            messages             custom_id
0  [{'content': '제가 편집할 내용이 있어요. 제가 작성한 텍스트는 다음과 ...  00000000000000000000
1  [{'content': '작성된 콘텐츠를 편집한다는 것이 실제로 무엇을 의미하며, ...  00000000000000000001
2  [{'content': '당신은 아이스크림을 아주 좋아하고 강아지들을 몹시 아끼는 ...  00000000000000000002
3  [{'content': '저는 최근에 사업을 시작한 35세 여성 사만다입니다. 저는...  00000000000000000003
4  [{'content': ' 귀하의 응답은 50단어 미만이어야 해요. 응답에 [for...  00000000000000000004

--- train-00001-of-00008.parquet ---

                                            messages             custom_id
0  [{'content': 'x와 y 변수 모두 1부터 20까지의 데이터에 대한 회귀선...  00000000000000057541
1  [{'content': '리스트 `x`와 정수 `k`를 입력으로 받아 `x`의 `k...  00000000000000057542
2  [{'content': '데이터 해석에서 상관 분석의 주요 목적은 무엇인가요?', ...  00000000000000057543
3  [{'content': '두 다항식의 도함수를 입력으로 받아 최대공약수를 반환하는 ...  00000000000000057544
4  [{'content': '저는 형사이며, 유력 호텔에서 발생한 살인 사건을 해결해야...  00000000000000057545

--- train-00002-of-00008.parquet ---

                                            messages             custom_id
0  [{'content': '리스트와 인덱스 범위를 인수로 받아, 주어진 범위의 요소를...  00000000000000115083
1  [{'content': '저는 미국 남북 전쟁의 경제적 영향에 대한 에세이를 작성하...  00000000000000115084
2  [{'content': '저는 텍스트 다시 쓰기를 위한 AI 어시스턴트에요. 입력된...  00000000000000115085
3  [{'content': '길이가 n인 이진 문자열을 입력으로 받아 해당 문자열이 1...  00000000000000115086
4  [{'content': '어쩌면 기초적인 개념이나 이론적인 수학 문제부터 시작하는 ...  00000000000000115087

--- train-00003-of-00008.parquet ---

                                            messages             custom_id
0  [{'content': '섭씨 온도를 화씨 온도로 변환하는 표를 나타내는 목록을 생...  00000000000000172628
1  [{'content': '간단한 언어에 대한 알고리즘을 구현하는 것은 종종 어려운 ...  00000000000000172629
2  [{'content': '피보나치 수열은 0과 1로 시작하며, 각 후속 숫자는 이전...  00000000000000172630
3  [{'content': '입력 텍스트의 주요 핵심 내용을 날짜나 위치와 같은 필수 ...  00000000000000172631
4  [{'content': '당신은 AI 어시스턴트이에요. 사용자가 당신에게 작업을 줄...  00000000000000172632

--- train-00004-of-00008.parquet ---

                                            messages             custom_id
0  [{'content': '저는 20년이 넘는 경험을 가진 숙련된 사립 탐정입니다. ...  00000000000000230173
1  [{'content': '문자열을 키로, 정수를 값으로 가지는 key-value 쌍...  00000000000000230174
2  [{'content': '다음은 n보다 작은 숫자 중에서 3 또는 5로 나누어 떨어...  00000000000000230175
3  [{'content': '두 자리의 양의 정수는 6으로 나누어 떨어져요. 그 자릿수...  00000000000000230176
4  [{'content': '특정 숫자가 2차원 배열에 있는지 어떻게 확인할 수 있나요...  00000000000000230177

--- train-00005-of-00008.parquet ---

                                            messages             custom_id
0  [{'content': '안녕하세요', 'content_en': 'Hello', '...  00000000000000287713
1  [{'content': '제공된 입력 텍스트의 주요 행동과 의도에 초점을 맞춰, 2...  00000000000000287714
2  [{'content': 'Python 함수 `get_tensor_size`를 작성해...  00000000000000287715
3  [{'content': '저는 도시 농업에 관한 750단어 에세이를 작성하고 있어요...  00000000000000287716
4  [{'content': '다음 등장인물의 행동을 문장으로 묘사해주세요.
사나운 개'...  00000000000000287717

--- train-00006-of-00008.parquet ---

                                            messages             custom_id
0  [{'content': '입력 텍스트에 대한 간결하고 객관적인 요약을 최대 세 문장...  00000000000000345254
1  [{'content': '귀하는 AI 어시스턴트이시요. 귀하에게 과제가 주어질 것이...  00000000000000345255
2  [{'content': '기술 분석을 위한 데이터 분석의 주요 유형은 무엇인가요?'...  00000000000000345256
3  [{'content': '다음 형식으로 코드 예시를 제공해주세요.

**Langua...  00000000000000345257
4  [{'content': ' 앨라배마 시골 지역의 작은 마을 고등학교 미식축구 코치의...  00000000000000345258

--- train-00007-of-00008.parquet ---

                                            messages             custom_id
0  [{'content': '귀하는 텍스트 재작성을 위한 AI 어시스턴트이시요. 입력된...  00000000000000402799
1  [{'content': '귀하는 사용자 쿼리와 관련된 제품 또는 서비스를 항상 제안...  00000000000000402800
2  [{'content': '달팽이가 20피트 우물 바닥에 있어요. 매일 3피트씩 기어...  00000000000000402801
3  [{'content': 'LeetCode의 'Container with most w...  00000000000000402802
4  [{'content': ' 귀하는 대형 공공 수족관에서 유지 보수 작업자로서 상어 ...  00000000000000402803

## 3. 결측치와 샘플 통계

각 Parquet 파일에서 최대 `SAMPLE_ROWS`개만 읽어 컬럼별 결측치와 문자열 길이를 확인합니다.

In [4]:
sample_tables = {}
for path in parquet_paths:
    batches = []
    for batch in pq.ParquetFile(path).iter_batches(batch_size=min(SAMPLE_ROWS, 1024)):
        batches.append(batch.to_pandas())
        if sum(len(x) for x in batches) >= SAMPLE_ROWS:
            break
    sample_tables[path.name] = pd.concat(batches, ignore_index=True).head(SAMPLE_ROWS) if batches else pd.DataFrame()

null_rows = []
length_rows = []
for name, table in sample_tables.items():
    for column in table.columns:
        null_rows.append({
            'file': name,
            'column': column,
            'sample_rows': len(table),
            'null_count': int(table[column].isna().sum()),
            'dtype': str(table[column].dtype),
        })
        if pd.api.types.is_string_dtype(table[column]):
            lengths = table[column].dropna().astype(str).str.len()
            if not lengths.empty:
                length_rows.append({
                    'file': name, 'column': column,
                    'min_chars': int(lengths.min()),
                    'median_chars': float(lengths.median()),
                    'max_chars': int(lengths.max()),
                })

print('결측치')
display(pd.DataFrame(null_rows))
print('문자열 길이')
display(pd.DataFrame(length_rows))

결측치

                            file       column  sample_rows  null_count   dtype
0   train-00000-of-00001.parquet  instruction         2000           0     str
1   train-00000-of-00001.parquet        input         2000           0     str
2   train-00000-of-00001.parquet       output         2000           0     str
3    test-00000-of-00001.parquet           id          108           0     str
4    test-00000-of-00001.parquet     messages          108           0  object
5    test-00000-of-00001.parquet     metadata          108           0  object
6   train-00000-of-00002.parquet     messages         2000           0  object
7   train-00001-of-00002.parquet     messages         2000           0  object
8   train-00000-of-00008.parquet     messages         2000           0  object
9   train-00000-of-00008.parquet    custom_id         2000           0     str
10  train-00001-of-00008.parquet     messages         2000           0  object
11  train-00001-of-00008.parquet    custom_id         2000           0     str
12  train-00002-of-00008.parquet     messages         2000           0  object
13  train-00002-of-00008.parquet    custom_id         2000           0     str
14  train-00003-of-00008.parquet     messages         2000           0  object
15  train-00003-of-00008.parquet    custom_id         2000           0     str
16  train-00004-of-00008.parquet     messages         2000           0  object
17  train-00004-of-00008.parquet    custom_id         2000           0     str
18  train-00005-of-00008.parquet     messages         2000           0  object
19  train-00005-of-00008.parquet    custom_id         2000           0     str
20  train-00006-of-00008.parquet     messages         2000           0  object
21  train-00006-of-00008.parquet    custom_id         2000           0     str
22  train-00007-of-00008.parquet     messages         2000           0  object
23  train-00007-of-00008.parquet    custom_id         2000           0     str

문자열 길이

,file,column,min_chars,median_chars,max_chars
0,train-00000-of-00001.parquet,instruction,42,42.0,43
1,train-00000-of-00001.parquet,input,12,108.0,296
2,train-00000-of-00001.parquet,output,2,21.0,44
3,test-00000-of-00001.parquet,id,11,12.0,35
4,train-00000-of-00008.parquet,custom_id,20,20.0,20
5,train-00001-of-00008.parquet,custom_id,20,20.0,20
6,train-00002-of-00008.parquet,custom_id,20,20.0,20
7,train-00003-of-00008.parquet,custom_id,20,20.0,20
8,train-00004-of-00008.parquet,custom_id,20,20.0,20
9,train-00005-of-00008.parquet,custom_id,20,20.0,20
10,train-00006-of-00008.parquet,custom_id,20,20.0,20
11,train-00007-of-00008.parquet,custom_id,20,20.0,20

## 4. 대화 메시지 구조와 role 분포

In [5]:
def message_roles(value):
    if isinstance(value, list):
        return [item.get('role') for item in value if isinstance(item, dict) and 'role' in item]
    return []

role_counts = Counter()
message_count_rows = []
for name, table in sample_tables.items():
    for column in ('messages', 'text'):
        if column not in table.columns:
            continue
        for value in table[column]:
            roles = message_roles(value)
            role_counts.update(roles)
            if roles:
                message_count_rows.append({'file': name, 'messages_per_row': len(roles)})

print('role 분포(샘플 기준)')
display(pd.DataFrame(role_counts.items(), columns=['role', 'count']).sort_values('count', ascending=False))
print('대화 턴 수(샘플 기준)')
display(pd.DataFrame(message_count_rows).groupby('file')['messages_per_row'].describe() if message_count_rows else 'messages 컬럼을 찾지 못했습니다.')

role 분포(샘플 기준)

Empty DataFrame
Columns: [role, count]
Index: []

대화 턴 수(샘플 기준)

'messages 컬럼을 찾지 못했습니다.'

## 5. JSONL 샘플

대형 JSONL 전체를 DataFrame으로 만들지 않고 앞부분 5개만 확인합니다.

In [6]:
jsonl_paths = sorted(RAW_DIR.rglob('*.jsonl'))
for path in jsonl_paths:
    print(f'--- {path.relative_to(ROOT)} ---')
    with path.open(encoding='utf-8') as f:
        for index, line in enumerate(f):
            if line.strip():
                print(json.dumps(json.loads(line), ensure_ascii=False, indent=2)[:3000])
                print()
            if index >= 4:
                break

--- data\raw\mkd-chanwoo\keural-rag-chatml-ko\keural_synthetic_sft_shard_0000.jsonl ---
{
  "text": "<|im_start|>user\nK-POP/K-Drama 관련상품(음반,도서,DVD)을\n영문/중문 으로 이용하실 수 있습니다.\nGlobal yesticket 모든 장르, 모두가 읽는 책 웅진 브랜드전\n2026년 04월 20일 ~ 2026년 07월 31일\n\"문화예술의 내일을 만들다\" - 예술나무 후원 캠페인\n2026년 04월 19일 ~ 2026년 06월 30일\n2026년 04월 13일 ~ 2026년 05월 30일\n2026년 04월 01일 ~ 2026년 04월 30일\n2026년 03월 05일 ~ 2026년 04월 30일\n2026년 04월 15일 ~ 2026년 04월 28일\n2026년 04월 14일 ~ 2026년 05월 14일\n2026년 04월 21일 ~ 2026년 06월 30일\n30명의 예스24 회원이 평가한 평균별점\n\nK-POP 및 K-Drama 관련 상품인 음반, 도서, DVD는 어떤 언어로 이용할 수 있습니까?\n<|im_end|>\n<|im_start|>assistant\n제시된 텍스트에 근거하여 질문에 대해 답변해 드리겠습니다.\n\nK-POP 및 K-Drama 관련 상품인 음반, 도서, DVD는 **영문(English)**과 **중문(Chinese)**으로 이용하실 수 있습니다.\n\n**[학습 포인트]**\n텍스트의 첫 번째 문장을 살펴보면, 해당 상품들이 지원하는 언어적 범위를 명확히 명시하고 있습니다. 이는 글로벌 이용자를 대상으로 서비스를 제공하고 있음을 알 수 있는 정보입니다.\n<|im_end|>",
  "source_name": "keural_synthetic_sft",
  "license": "cc-by-4.0",
  "n_tokens": 444
}

{
  "text": "<|im_start|>user\n클래식, 재즈, 월드뮤직 등 다양한 음악 공연과 음반에 대한 리뷰, 정보, 칼럼을 제공합니다.\n미술, 디자인, 전시 등 예술 작품과 전시 정보를 소개하고, 깊이 있는 해설과 글로벌 아트 소식을 전합니다.\n연극, 뮤지컬, 영화 등 무대예술과 영상예술의 리뷰, 프로그램 정보, 뉴스와 인터뷰를 제공합니다.\n예술과 인문학, 문화 관련 서적과 도서 정보를 소개하고, 서평과 저자 인터뷰를 제공합니다.\n해당 도서에 대한 전문가 리뷰가 아직 없습니다!\n해당 도서에 대한 회원 리뷰가아직 없습니다!\n좌우로 움직여 별점을 채워주세요.\n반복 등록 시 본 사이트 이용이제한될 수 있습니다.\n\n이 서비스는 음악, 미술, 무대예술, 도서 등 어떤 분야의 예술 및 문화 정보를 제공합니까?\n<|im_end|>\n<|im_start|>assistant\n제시된 텍스트를 바탕으로 답변해 드리겠습니다.\n\n해당 서비스는 다음과 같이 네 가지 주요 분야의 예술 및 문화 정보를 제공하고 있습니다.\n\n1. **음악 분야**: 클래식, 재즈, 월드뮤직 등 다양한 장르의 음악 공연과 음반에 관한 리뷰, 정보, 칼럼을 제공합니다.\n2. **미술 분야**: 미술, 디자인, 전시 등 예술 작품과 전시 정보를 소개하며, 이에 대한 깊이 있는 해설과 글로벌 아트 소식을 전달합니다.\n3. **무대 및 영상예술 분야**: 연극, 뮤지컬, 영화를 포함한 무대예술과 영상예술의 리뷰, 프로그램 정보, 뉴스 및 인터뷰를 제공합니다.\n4. **도서 분야**: 예술, 인문학, 문화 관련 서적과 도서 정보를 소개하며, 서평과 저자 인터뷰를 함께 제공합니다.\n<|im_end|>",
  "source_name": "keural_synthetic_sft",
  "license": "cc-by-4.0",
  "n_tokens": 328
}

{
  "text": "<|im_start|>user\n📗 경기순환 주식 투자: 경제 흐름을 읽어내어 투자하자\n경기순환 투자는 경기 순환에 따라 특정 업종 또는 자산에 집중하는 전략으로, 경제의 상황에 따라 투자 방향을 조정하는 투자 전략을 의미합니다. 이 글에서는 경기순환 투자에 대해 자세히 알아보겠습니다.\n📄 경기순환 투자란 무엇인가?\n경기순환 투자는 경제의 흐름을 파악하여 투자 전략을 결정하는 방법입니다. 이것은 경기의 다섯 단계를 고려하며, 이 단계에 따라 특정 산업 또는 자산에 투자를 집중하는 것을 포함합니다.\n💡 경기가 좋을 때와 나쁠 때의 투자 전략\n경기순환 투자는 경제의 움직임을 파악하고 투자전략을 조절함으로써 투자자에게 이점을 제공하는 전략 중 하나입니다. 그러나 경기를 정확하게 예측하는 것은 어려울 수 있으므로 신중하게 고려해야 합니다.\n————더 많은 블록체인 경제 주식 코인 퀀트 정보 :\n\n경기순환 투자의 정의와 함께 투자자가 고려해야 할 핵심 요소는 무엇입니까?\n<|im_end|>\n<|im_start|>assistant\n제시된 텍스트를 바탕으로 답변해 드리겠습니다.\n\n**경기순환 투자의 정의와 핵심 고려 요소**\n\n**1. 경기순환 투자의 정의**\n경기순환 투자란 경제의 전반적인 흐름을 읽어내어, 현재의 경제 상황에 따라 투자 방향을 조정하는 전략을 의미합니다. 즉, 경제가 순환하는 흐름에 맞춰 특정 업종이나 자산에 집중적으로 투자함으로써 이점을 얻고자 하는 방법입니다.\n\n**2. 투자자가 고려해야 할 핵심 요소**\n경기순환 투자를 실행할 때 투자자는 다음과 같은 핵심 요소를 반드시 고려해야 합니다.\n\n* **경기의 단계 파악:** 경기는 총 다섯 단계로 구분됩니다. 투자자는 현재 경제가 이 다섯 단계 중 어느 지점에 위치해 있는지를 파악해야 하며, 해당 단계에 따라 유망한 특정 산업이나 자산이 무엇인지 결정해야 합니다.\n* **경제 흐름과 투자 방향의 일치:** 경제의 움직임에 따라 투자 전략을 유연하게 조절하는 것이 중요합니다.\n* **예측의 불확실성 유의:** 경기의 흐름을 정확하게 예측하는 것은 매우 어려운 일입니다. 따라서 경기를 예측하여 투자할 때는 신중한 고려가 필요합니다.\n<|im_end|>",
  "source_name": "keural_synthetic_sft",
  "license": "cc-by-4.0",
  "n_tokens": 389
}

{
  "text": "<|im_start|>user\n자본소득이 근로소득을 넘어서는 날이 우리의 경제적 독립기념일입니다.\n저는 미국 주식 투자를 시작한 지 만 2년이 조금 넘었습니다. 미국 주식 투자를 처음 접할 때 느꼈던 어려운 점과, 저만의 투자철학이나 투자방식에 대해 여러 채널(유튜브, ZUM, 브런치 등)을 통해 초보 입문자분들과 공유해가고 있습니다.\n달러라는 외국통화를 환전하는 것부터, 티커나 SPY, QQQ 같은 생소한 용어, 밤 10~11시에 개장하는 주식 시장, 그리고 한국에는 없는 서머타임 탓에 계절마다 바뀌는 개장 시간 등… 다른 문화의 해외 시장에 투자하다 보니 어려운 점이 한두 개가 아니었습니다.저 역시 미국 주식에 투자한 경험이 얼마 되지 않다 보니 처음 투자를 시작하는 분들의 어려움에 충분히 공감합니다. 그래서 제가 투자하며 경험한 것들을 나누고 서로 격려하면서 성공한 투자자가 되기 위한 먼 길을 함께 걸어가고자 글을 쓰게 되었습니다.\n오늘은 제가 미국 주식에 투자하는 투자전략 3가지에 대해 공유 드리겠습니다.\n이 글은 제가 원고를 기고하고 있는 '줌 투자노트'에서 자세히 읽어보실 수 있습니다.\n유튜브로 시청을 원하시면 아래 링크를 클릭해주세요!\n\n작성자가 미국 주식 투자를 처음 시작할 때 겪었던 구체적인 어려움에는 어떤 것들이 있습니까?\n<|im_end|>\n<|im_start|>assistant\n작성자가 미국 주식 투자를 처음 시작할 때 경험했던 구체적인 어려움은 다음과 같이 네 가지 측면으로 정리할 수 있습니다.\n\n첫째, **환전의 번거로움**입니다. 국내 통화가 아닌 '달러'라는 외국 통화로 환전하여 투자해야 한다는 점이 초기 단계에서의 어려움 중 하나였습니다.\n\n둘째, **생소한 전문 용어의 습득**입니다. 주식 종목을 식별하는 '티커(Ticker)'나, 특정 ETF를 나타내는 'SPY', 'QQQ'와 같은 미국 시장 특유의 용어들이 익숙하지 않아 어려움을 겪었습니다.\n\n셋째, **시장 운영 시간의 차이**입니다. 한국 시간 기준으로 밤 10~11시에 주식 시장이 개장하기 때문에, 일상적인 생활 시간대와 투자 시간이 일치하지 않는 점이 어려움으로 작용했습니다.\n\n넷째, **서머타임(일광절약시간제) 적용**입니다. 한국에는 없는 서머타임 제도로 인해 계절마다 주식 시장의 개장 시간이 변동되는 점 또한 해외 시장 투자자로서 적응해야 할 까다로운 요소였습니다.\n\n이러한 경험들은 작성자가 타 문화권의 금융 시장에 접근할 때 겪을 수 있는 실무적, 환경적 제약들을 잘 보여줍니다.\n<|im_end|>",
  "source_name": "keural_synthetic_sft",
  "license": "cc-by-4.0",
  "n_tokens": 496
}

{
  "text": "<|im_start|>user\n[strategic asset allocation]주식 투자를 할 때 장기적인 비율을 정하고 이를 지키는 방법으로 자산을 배분하는 것을 말한다. 반면 단기적인 주가의 움직임을 반영하여 그때 그때 비율을 조정하는 기법을 전술적 배분(tactical asset allocation)이라 한다.\n지능형원격검침[advanced electricity metering, AEM]\n전력시스템과 정보통신기술(ICT)을 연동해 에너지 사용 현황을 실시간으로 확인하고 조작할 ...\n중국 정부가 수출을 장려하기 위해 1994년부터 적용했던 외국기업 우대 조치의 하나. 가공...\n옥수수 등에서 추출한 다당류 탄수화물이다. 설탕을 대신한 단맛과 매끈한 질감을 내기 위해 ...\n중기채[medium term note, MTN]\n차입액의 한도와 기간을 설정하고 이 범위내에서 수시로 채권(note)을 발행하는 중 · 장...\n\n전략적 자산 배분(strategic asset allocation)과 전술적 배분(tactical asset allocation)의 차이점은 무엇인가요?\n<|im_end|>\n<|im_start|>assistant\n주식 투자 전략에서 **전략적 자산 배분(strategic asset allocation)**과 **전술적 배분(tactical asset allocation)**은 자산의 비율을 결정하고 조정하는 '기간'과 '방식' 측면에서 다음과 같은 차이가 있습니다.\n\n**1. 전략적 자산 배분 (Strategic Asset Allocation)**\n* **개념:** 주식 투자를 할 때 장기적인 관점에서 자산의 배분 비율을 미리 정해두는 방식입니다.\n* **핵심 특징:** 일시적인 시장 변화에 흔들리기보다는, 사전에 설정한 **장기적인 목표 비율을 지속적으로 지키는 것**에 중점을 둡니다.\n\n**2. 전술적 배분 (Tactical Asset Allocation)**\n* **개념:** 시장의 상황에 따라 자산의 비율을 유동적으로 조정하는 기법입니다.\n* **핵심 특징:** 장기적인 계획에만 머무르는 것이 아니라, **단기적인 주가의 움직임을 반영**하여 그때그때 상황에 맞게 자산 비중을 변화시키는 능동적인 방식을 취합니다.\n\n**[요약 비교]**\n| 구분 | 전략적 자산 배분 | 전술적 배분 |\n| :--- | :--- | :--- |\n| **관점** | 장기적 | 단기적 |\n| **운용 방식** | 정해진 비율을 유지하며 지킴 | 주가 움직임에 따라 비율을 조정함 |\n<|im_end|>",
  "source_name": "keural_synthetic_sft",
  "license": "cc-by-4.0",
  "n_tokens": 454
}

## 해석 메모

이 노트북의 결과를 바탕으로 다음을 결정합니다.

1. 공통 변환 포맷을 `messages: [{role, content}]`로 할지 결정
2. `instruction/input/output`, `question/answer`, `text` 컬럼의 매핑 규칙 작성
3. 빈 문자열·비정상 role·너무 긴 샘플 필터 기준 결정
4. 중복 제거 전에 원문 파일별 보존 비율을 기록
5. SFT 데이터와 사전학습 데이터를 분리하여 관리